<a href="https://colab.research.google.com/github/subodh2708/PYTHON/blob/main/Assignment_Pandas_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <u> Use only those concepts which have been taught till now </u>

# <b> Problem 1: Import Pandas and Numpy in the notebook </b>

In [2]:
# Import statements

import numpy as np 
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# <b> Problem 2 : Load the automobile_data.csv kept in the shared folder

In [4]:
# Mount your drive and read the csv file. Make sure you are using the correct file path
working_dir_path = "/content/drive/MyDrive/Colab Notebooks/alma better/week 3/assignments/M1W3D3/Copy of dat/"
df = pd.read_csv(working_dir_path + "automobile_data.csv")

# <b> Problem 3 : Do a basic inspection and print the first and last 15 rows of your dataframe

In [5]:
# Your code here
df.head(15)

    symboling normalized-losses         make  ... city-mpg highway-mpg  price
0           3                 ?  alfa-romero  ...       21          27  13495
1           3                 ?  alfa-romero  ...       21          27  16500
2           1                 ?  alfa-romero  ...       19          26  16500
3           2               164         audi  ...       24          30  13950
4           2               164         audi  ...       18          22  17450
5           2                 ?         audi  ...       19          25  15250
6           1               158         audi  ...       19          25  17710
7           1                 ?         audi  ...       19          25  18920
8           1               158         audi  ...       17          20  23875
9           0                 ?         audi  ...       16          22      ?
10          2               192          bmw  ...       23          29  16430
11          0               192          bmw  ...       23          29  16925
12          0               188          bmw  ...       21          28  20970
13          0               188          bmw  ...       21          28  21105
14          1                 ?          bmw  ...       20          25  24565

[15 rows x 26 columns]

In [6]:
df.tail(15)

     symboling normalized-losses        make  ... city-mpg highway-mpg  price
190          3               256  volkswagen  ...       24          29   9980
191          0                 ?  volkswagen  ...       19          24  13295
192          0                 ?  volkswagen  ...       33          38  13845
193          0                 ?  volkswagen  ...       25          31  12290
194         -2               103       volvo  ...       23          28  12940
195         -1                74       volvo  ...       23          28  13415
196         -2               103       volvo  ...       24          28  15985
197         -1                74       volvo  ...       24          28  16515
198         -2               103       volvo  ...       17          22  18420
199         -1                74       volvo  ...       17          22  18950
200         -1                95       volvo  ...       23          28  16845
201         -1                95       volvo  ...       19          25  19045
202         -1                95       volvo  ...       18          23  21485
203         -1                95       volvo  ...       26          27  22470
204         -1                95       volvo  ...       19          25  22625

[15 rows x 26 columns]

# <b>Problem 4 : You need to clean the data a little bit now. Replace all column values with the values <code>?</code> and <code>n.a</code> with <code>NaN</code>

In [14]:
# Your code here
def replace_values(column_value):
  for value in ["?","n.a"]:
    if value in column_value:
      new_value = column_value.replace(value,'NaN')

      return new_value

In [16]:
df.apply(lambda x:replace_values(x),axis =1)

0      None
1      None
2      None
3      None
4      None
       ...
200    None
201    None
202    None
203    None
204    None
Length: 205, dtype: object

# <b>Problem 5 : Print the company name which manufactured the most expensive car. Also print the price of the most expensive car

In [ ]:
# Your code here

# <b>Problem 6 : Calculate maximum horsepowers for each company. </b>

In [ ]:
# Your code here

# <b> Problem 7 : Print the total number of cars manufactured by each company

In [ ]:
# Your code here

# <b> Problem 8 : Create a new column for the updated price. This updated price will be calculated on top of the given price - if the engine is in front, price will be same else if the engine is in rear, price will be doubled </b>

In [ ]:
# Your code here. Use apply and lambda

# <b>Problem 9 : Sort the dataframe by car and price columns

In [ ]:
# Your code here

# <b> Problem 10 : Create a new column which stores the number of doors in a car as integers.

In [ ]:
# Your code here. Use apply

# <b>Problem 11 : Concatenate the two data frames given below firstly row wise and secondly column wise.</b>

<code>GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}</code>

<code>japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}</code>

In [ ]:
# Your code here